import { Question, Team, GameSettings } from '../types/game';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-red',
    name: 'Team Red',
    number: 101,
    avatar: 'runner_boy',
    color: '#EF4444',
    secondaryColor: '#B91C1C',
    position: 0,
    score: 0,
    correctAnswers: 0,
    wrongAnswers: 0,
    streak: 0,
    powerCard: {
      id: 'double_move',
      name: 'Double Move',
      description: 'Next correct answer gives double movement steps',
      icon: '⚡',
      used: false,
    },
  },
  {
    id: 'team-blue',
    name: 'Team Blue',
    number: 202,
    avatar: 'runner_girl',
    color: '#3B82F6',
    secondaryColor: '#1D4ED8',
    position: 0,
    score: 0,
    correctAnswers: 0,
    wrongAnswers: 0,
    streak: 0,
    powerCard: {
      id: 'bonus_step',
      name: 'Bonus Step',
      description: 'Instantly grants +2 movement steps',
      icon: '🚀',
      used: false,
    },
  },
  {
    id: 'team-green',
    name: 'Team Green',
    number: 303,
    avatar: 'mascot_bear',
    color: '#10B981',
    secondaryColor: '#047857',
    position: 0,
    score: 0,
    correctAnswers: 0,
    wrongAnswers: 0,
    streak: 0,
    powerCard: {
      id: 'safe_answer',
      name: 'Safe Answer',
      description: 'Protects streak if team makes an incorrect guess',
      icon: '🛡️',
      used: false,
    },
  },
  {
    id: 'team-yellow',
    name: 'Team Yellow',
    number: 404,
    avatar: 'astronaut',
    color: '#F59E0B',
    secondaryColor: '#B45309',
    position: 0,
    score: 0,
    correctAnswers: 0,
    wrongAnswers: 0,
    streak: 0,
    powerCard: {
      id: 'second_chance',
      name: 'Second Chance',
      description: 'Provides a second chance retry if answer is incorrect',
      icon: '🔄',
      used: false,
    },
  },
];

export const EXTRA_AVATAR_TEMPLATES: Omit<Team, 'id' | 'position' | 'score' | 'correctAnswers' | 'wrongAnswers' | 'streak'>[] = [
  {
    name: 'Team Purple',
    number: 505,
    avatar: 'robot',
    color: '#A855F7',
    secondaryColor: '#7E22CE',
  },
  {
    name: 'Team Orange',
    number: 606,
    avatar: 'champion',
    color: '#F97316',
    secondaryColor: '#C2410C',
  },
  {
    name: 'Team Pink',
    number: 707,
    avatar: 'runner_girl',
    color: '#EC4899',
    secondaryColor: '#BE185D',
  },
  {
    name: 'Team Cyan',
    number: 808,
    avatar: 'astronaut',
    color: '#06B6D4',
    secondaryColor: '#0E7490',
  },
];

export const SCIENCE_HUMAN_BODY_QUESTIONS: Question[] = [
  {
    id: 'q1',
    question: 'Which organ pumps blood around the entire body?',
    options: {
      A: 'Brain',
      B: 'Heart',
      C: 'Lung',
      D: 'Stomach',
    },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The heart is a muscular organ that beats continuously to circulate oxygen-rich blood throughout the body.',
    topic: 'Circulatory System',
  },
  {
    id: 'q2',
    question: 'Which organ is mainly used for breathing and exchanging gases?',
    options: {
      A: 'Heart',
      B: 'Stomach',
      C: 'Lungs',
      D: 'Brain',
    },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Our pair of lungs inhale oxygen from the air and exhale carbon dioxide waste.',
    topic: 'Respiratory System',
  },
  {
    id: 'q3',
    question: 'Which vital organ controls our thoughts, memories, and body movement?',
    options: {
      A: 'Brain',
      B: 'Heart',
      C: 'Lung',
      D: 'Bone',
    },
    correctAnswer: 'A',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The brain acts as the central control computer of our nervous system.',
    topic: 'Nervous System',
  },
  {
    id: 'q4',
    question: 'What hard bone structure protects our delicate brain from injury?',
    options: {
      A: 'Ribcage',
      B: 'Pelvis',
      C: 'Skull',
      D: 'Spine',
    },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The skull (cranium) forms a protective helmet of fused bones shielding the brain.',
    topic: 'Skeletal System',
  },
  {
    id: 'q5',
    question: 'Which organ churns food and produces digestive juices to break down meals?',
    options: {
      A: 'Stomach',
      B: 'Heart',
      C: 'Windpipe',
      D: 'Kidney',
    },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The stomach breaks down food mechanically and chemically using gastric acids and enzymes.',
    topic: 'Digestive System',
  },
  {
    id: 'q6',
    question: 'What connects two bones together at flexible joints in the body?',
    options: {
      A: 'Skin',
      B: 'Ligaments',
      C: 'Hair',
      D: 'Nerves',
    },
    correctAnswer: 'B',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'Ligaments are strong elastic bands of tissue that connect bone to bone at our joints.',
    topic: 'Musculoskeletal',
  },
  {
    id: 'q7',
    question: 'Which sense organ detects sound vibrations in the air around us?',
    options: {
      A: 'Tongue',
      B: 'Eyes',
      C: 'Ears',
      D: 'Nose',
    },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Our ears collect sound waves and translate vibrations into neural signals sent to the brain.',
    topic: 'Sensory Organs',
  },
  {
    id: 'q8',
    question: 'How many permanent teeth does a typical adult human develop?',
    options: {
      A: '20',
      B: '28',
      C: '32',
      D: '40',
    },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'An adult human typically has 32 permanent teeth, including molars and wisdom teeth.',
    topic: 'Dentition',
  },
  {
    id: 'q9',
    question: 'Which blood vessels carry freshly oxygenated blood AWAY from the heart?',
    options: {
      A: 'Veins',
      B: 'Arteries',
      C: 'Capillaries',
      D: 'Valves',
    },
    correctAnswer: 'B',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'Arteries carry blood away from the heart to all parts of the body under high pressure.',
    topic: 'Circulatory System',
  },
  {
    id: 'q10',
    question: 'Which body system provides structural support, protection, and allows locomotion with muscles?',
    options: {
      A: 'Skeletal System',
      B: 'Digestive System',
      C: 'Urinary System',
      D: 'Integumentary System',
    },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The skeletal system consists of over 200 bones providing framework, marrow, and protection.',
    topic: 'Anatomy',
  },
  {
    id: 'q11',
    question: 'What essential gas do our red blood cells pick up when air fills the lungs?',
    options: {
      A: 'Helium',
      B: 'Carbon Dioxide',
      C: 'Nitrogen',
      D: 'Oxygen',
    },
    correctAnswer: 'D',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Oxygen (O2) binds to hemoglobin in red blood cells to fuel cells across the body.',
    topic: 'Respiration',
  },
  {
    id: 'q12',
    question: 'Which bean-shaped organs filter liquid waste from our bloodstream to make urine?',
    options: {
      A: 'Lungs',
      B: 'Kidneys',
      C: 'Spleen',
      D: 'Pancreas',
    },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The kidneys continually filter blood, remove waste products, balance hydration, and create urine.',
    topic: 'Excretory System',
  },
  {
    id: 'q13',
    question: 'What is the largest organ of the human body that protects us from germs and sunlight?',
    options: {
      A: 'Liver',
      B: 'Brain',
      C: 'Skin',
      D: 'Large Intestine',
    },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The skin is the largest organ, acting as a waterproof protective barrier and regulating body temperature.',
    topic: 'Integumentary System',
  },
  {
    id: 'q14',
    question: 'What fluid in the mouth begins chemical digestion by breaking down starches?',
    options: {
      A: 'Saliva',
      B: 'Bile',
      C: 'Gastric acid',
      D: 'Mucus',
    },
    correctAnswer: 'A',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Saliva contains the enzyme amylase, which begins breaking down starches into simpler sugars in the mouth.',
    topic: 'Digestive System',
  },
  {
    id: 'q15',
    question: 'Which tiny blood vessels have walls only one cell thick to allow nutrient and oxygen exchange?',
    options: {
      A: 'Arteries',
      B: 'Capillaries',
      C: 'Veins',
      D: 'Aortas',
    },
    correctAnswer: 'B',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'Capillaries are microscopic vessels where oxygen, nutrients, and waste diffuse between blood and tissues.',
    topic: 'Circulatory System',
  },
  {
    id: 'q16',
    question: 'What connects bones together at joints throughout the body?',
    options: {
      A: 'Tendons',
      B: 'Ligaments',
      C: 'Cartilage',
      D: 'Neurons',
    },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Ligaments connect bone to bone at joints, while tendons connect muscle to bone.',
    topic: 'Skeletal System',
  },
  {
    id: 'q17',
    question: 'Which organ produces insulin to regulate glucose (sugar) levels in the bloodstream?',
    options: {
      A: 'Pancreas',
      B: 'Gallbladder',
      C: 'Thyroid',
      D: 'Kidney',
    },
    correctAnswer: 'A',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'The pancreas produces the hormone insulin to help cells absorb sugar from the blood for energy.',
    topic: 'Endocrine System',
  },
  {
    id: 'q18',
    question: 'How many chambers are inside a healthy human heart?',
    options: {
      A: '2',
      B: '3',
      C: '4',
      D: '6',
    },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The heart has 4 chambers: two upper atria and two lower ventricles.',
    topic: 'Circulatory System',
  },
  {
    id: 'q19',
    question: 'What is the main dome-shaped muscle located below the lungs that contracts during inhalation?',
    options: {
      A: 'Diaphragm',
      B: 'Biceps',
      C: 'Abdominals',
      D: 'Trachea',
    },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The diaphragm contracts and flattens downwards, creating negative pressure that draws air into the lungs.',
    topic: 'Respiratory System',
  },
  {
    id: 'q20',
    question: '★ BONUS QUESTION: What is the longest and strongest bone in the entire human body?',
    options: {
      A: 'Humerus (Arm)',
      B: 'Femur (Thigh bone)',
      C: 'Tibia (Shin bone)',
      D: 'Spine (Vertebrae)',
    },
    correctAnswer: 'B',
    difficulty: 'Bonus',
    points: 50,
    movementSteps: 5,
    explanation: 'The femur (thigh bone) is the longest, heaviest, and strongest bone in the human body.',
    topic: 'Skeletal System',
  },
  {
    id: 'q21',
    question: 'What is the colored, circular part of the eye that controls how much light enters the pupil?',
    options: { A: 'Cornea', B: 'Iris', C: 'Retina', D: 'Lens' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The iris contains pigments giving our eyes color and muscles that adjust pupil size.',
    topic: 'Vision & Eyes',
  },
  {
    id: 'q22',
    question: 'Which blood cells help fight infections and destroy harmful bacteria in the body?',
    options: { A: 'Red blood cells', B: 'White blood cells', C: 'Platelets', D: 'Plasma' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'White blood cells (leukocytes) are the key defenders of our immune system.',
    topic: 'Immune System',
  },
  {
    id: 'q23',
    question: 'What tiny cell fragments in the blood help clot wounds and stop bleeding?',
    options: { A: 'Platelets', B: 'Hemoglobin', C: 'Antibodies', D: 'Hormones' },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Platelets clump together at the site of a cut to form a plug and initiate blood clotting.',
    topic: 'Circulatory System',
  },
  {
    id: 'q24',
    question: 'Where does most chemical digestion and nutrient absorption occur in our digestive tract?',
    options: { A: 'Stomach', B: 'Small Intestine', C: 'Large Intestine', D: 'Esophagus' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The small intestine absorbs roughly 90% of nutrients from digested food into the bloodstream.',
    topic: 'Digestive System',
  },
  {
    id: 'q25',
    question: 'What is the windpipe that carries air from the throat down into the lungs called?',
    options: { A: 'Esophagus', B: 'Bronchiole', C: 'Trachea', D: 'Larynx' },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The trachea is a sturdy tube reinforced with cartilage rings that carries air to the lungs.',
    topic: 'Respiratory System',
  },
  {
    id: 'q26',
    question: 'Which organ produces bile to help break down fats during digestion?',
    options: { A: 'Liver', B: 'Kidney', C: 'Spleen', D: 'Lungs' },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The liver continuously produces bile, which is stored in the gallbladder and released into the intestine.',
    topic: 'Digestive System',
  },
  {
    id: 'q27',
    question: 'What type of blood vessel carries deoxygenated blood back toward the heart?',
    options: { A: 'Arteries', B: 'Veins', C: 'Capillaries', D: 'Aortas' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Veins return blood back to the heart, featuring one-way valves to prevent backflow.',
    topic: 'Circulatory System',
  },
  {
    id: 'q28',
    question: 'Which tough, flexible tissue cushions the ends of bones at joints and forms the nose tip?',
    options: { A: 'Tendon', B: 'Cartilage', C: 'Ligament', D: 'Marrow' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Cartilage is a firm, smooth tissue that reduces friction between bones at joints.',
    topic: 'Skeletal System',
  },
  {
    id: 'q29',
    question: 'What is the voice box containing the vocal cords located in our throat called?',
    options: { A: 'Pharynx', B: 'Larynx', C: 'Trachea', D: 'Epiglottis' },
    correctAnswer: 'B',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'The larynx houses the vocal folds that vibrate when air passes through to produce sound.',
    topic: 'Respiratory System',
  },
  {
    id: 'q30',
    question: 'What is the primary function of the large intestine (colon)?',
    options: { A: 'Absorb water from indigestible food', B: 'Produce digestive enzymes', C: 'Pump blood', D: 'Filter airborne dust' },
    correctAnswer: 'A',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The large intestine reabsorbs water and electrolytes, turning liquid waste into solid stool.',
    topic: 'Digestive System',
  },
  {
    id: 'q31',
    question: 'What protective skull bones surround and shield our brain?',
    options: { A: 'Rib cage', B: 'Cranium', C: 'Pelvis', D: 'Sternum' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The cranium is the upper part of the skull enclosing and safeguarding the brain.',
    topic: 'Skeletal System',
  },
  {
    id: 'q32',
    question: 'What liquid inside our joints acts as a natural lubricant to prevent friction?',
    options: { A: 'Synovial fluid', B: 'Saliva', C: 'Lymph', D: 'Bile' },
    correctAnswer: 'A',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'Synovial fluid is a thick, egg-white-like liquid that cushions joints and nourishes cartilage.',
    topic: 'Joints & Movement',
  },
  {
    id: 'q33',
    question: 'Which nerve transmits visual signals from the eye to the visual cortex in the brain?',
    options: { A: 'Auditory nerve', B: 'Optic nerve', C: 'Olfactory nerve', D: 'Sciatic nerve' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The optic nerve carries more than a million nerve fibers carrying image signals from the retina.',
    topic: 'Nervous System',
  },
  {
    id: 'q34',
    question: 'What is the master gland at the base of the brain that regulates hormone production called?',
    options: { A: 'Pituitary gland', B: 'Thyroid gland', C: 'Adrenal gland', D: 'Pancreas' },
    correctAnswer: 'A',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'The pea-sized pituitary gland releases hormones that control growth, metabolism, and other glands.',
    topic: 'Endocrine System',
  },
  {
    id: 'q35',
    question: 'What is the thin flap of cartilage that covers the windpipe during swallowing to prevent choking?',
    options: { A: 'Uvula', B: 'Epiglottis', C: 'Tonsil', D: 'Adenoid' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The epiglottis folds down over the entrance of the trachea when we swallow food or liquids.',
    topic: 'Digestive & Respiratory',
  },
  {
    id: 'q36',
    question: 'Which microscopic air sacs in the lungs are responsible for gas exchange with blood capillaries?',
    options: { A: 'Bronchi', B: 'Alveoli', C: 'Cilia', D: 'Pleurals' },
    correctAnswer: 'B',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'Humans have roughly 300 million tiny alveoli that provide a vast surface area for oxygen uptake.',
    topic: 'Respiratory System',
  },
  {
    id: 'q37',
    question: 'What mineral is essential for building and maintaining strong bones and teeth?',
    options: { A: 'Iron', B: 'Calcium', C: 'Sodium', D: 'Zinc' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'About 99% of the body’s calcium is stored in bones and teeth to provide strength and structure.',
    topic: 'Nutrition & Bones',
  },
  {
    id: 'q38',
    question: 'What protein pigment in red blood cells binds to oxygen and gives blood its bright red color?',
    options: { A: 'Melanin', B: 'Hemoglobin', C: 'Keratin', D: 'Collagen' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Hemoglobin contains iron atoms that attract and hold oxygen molecules as blood circulates.',
    topic: 'Circulatory System',
  },
  {
    id: 'q39',
    question: 'What type of muscle makes up the walls of the heart and never tires?',
    options: { A: 'Skeletal muscle', B: 'Smooth muscle', C: 'Cardiac muscle', D: 'Voluntary muscle' },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Cardiac muscle is an involuntary, striated muscle found exclusively in the heart wall.',
    topic: 'Muscular System',
  },
  {
    id: 'q40',
    question: '★ BONUS QUESTION: What is the fastest nerve impulse speed recorded in the human nervous system?',
    options: { A: 'Around 10 km/h', B: 'Around 120 km/h', C: 'Over 400 km/h (120 m/s)', D: 'Speed of light' },
    correctAnswer: 'C',
    difficulty: 'Bonus',
    points: 50,
    movementSteps: 5,
    explanation: 'Myelinated motor neurons can transmit electrical action potentials at speeds exceeding 400 km/h (120 m/s)!',
    topic: 'Nervous System',
  },
  {
    id: 'q41',
    question: 'Which part of the brain controls balance, posture, and muscle coordination for walking?',
    options: { A: 'Cerebrum', B: 'Cerebellum', C: 'Brainstem', D: 'Hypothalamus' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'The cerebellum (little brain) coordinates complex voluntary movements and maintains balance.',
    topic: 'Brain & Nervous System',
  },
  {
    id: 'q42',
    question: 'What protective liquid produced by glands in the eyes flushes out debris and lubricates the cornea?',
    options: { A: 'Tears', B: 'Saliva', C: 'Mucus', D: 'Sweat' },
    correctAnswer: 'A',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Lacrimal glands produce tears containing enzymes like lysozyme that destroy bacteria.',
    topic: 'Sensory Organs',
  },
  {
    id: 'q43',
    question: 'Which organ filters old red blood cells and helps store immune white blood cells?',
    options: { A: 'Spleen', B: 'Gallbladder', C: 'Appendix', D: 'Pancreas' },
    correctAnswer: 'A',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'The spleen filters blood, recycles iron from damaged red cells, and mounts immune responses.',
    topic: 'Lymphatic & Immune',
  },
  {
    id: 'q44',
    question: 'What is the tough outer white layer that surrounds and protects the eyeball?',
    options: { A: 'Sclera', B: 'Pupil', C: 'Retina', D: 'Cornea' },
    correctAnswer: 'A',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'The sclera is the dense fibrous white outer coat of the eyeball that maintains eye shape.',
    topic: 'Sensory Organs',
  },
  {
    id: 'q45',
    question: 'How many ribs does a typical human rib cage have in total (pairs)?',
    options: { A: '10 ribs (5 pairs)', B: '16 ribs (8 pairs)', C: '24 ribs (12 pairs)', D: '30 ribs (15 pairs)' },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Both men and women normally have 24 ribs arranged in 12 matching pairs.',
    topic: 'Skeletal System',
  },
  {
    id: 'q46',
    question: 'What substance produced by sebaceous glands waterproofs and moisturizes our skin and hair?',
    options: { A: 'Keratin', B: 'Sebum (Natural oil)', C: 'Sweat', D: 'Bile' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Sebum is an oily substance that prevents skin from drying out and inhibits harmful bacterial growth.',
    topic: 'Skin & Integumentary',
  },
  {
    id: 'q47',
    question: 'Which chamber of the heart pumps oxygen-rich blood out to the whole body via the aorta?',
    options: { A: 'Right Atrium', B: 'Right Ventricle', C: 'Left Atrium', D: 'Left Ventricle' },
    correctAnswer: 'D',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: 'The left ventricle has the thickest muscle walls because it pumps blood throughout the entire systemic circulation.',
    topic: 'Circulatory System',
  },
  {
    id: 'q48',
    question: 'What is the primary gas released as a metabolic waste product when we exhale?',
    options: { A: 'Oxygen', B: 'Carbon Dioxide (CO2)', C: 'Carbon Monoxide', D: 'Hydrogen' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Cellular respiration produces carbon dioxide, which our blood carries to the lungs to be exhaled.',
    topic: 'Respiration',
  },
  {
    id: 'q49',
    question: 'What connects skeletal muscles directly to bones to produce movement when muscles contract?',
    options: { A: 'Tendons', B: 'Ligaments', C: 'Arteries', D: 'Nerves' },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Tendons are strong fibrous cords that anchor muscles to bones (e.g., the Achilles tendon).',
    topic: 'Muscular System',
  },
  {
    id: 'q50',
    question: '★ GRAND FINALE BONUS: Approximately how many cells make up an adult human body?',
    options: { A: '1 million', B: '1 billion', C: '37 trillion', D: '500 trillion' },
    correctAnswer: 'C',
    difficulty: 'Bonus',
    points: 50,
    movementSteps: 5,
    explanation: 'Scientists estimate the human body is comprised of approximately 37 trillion cooperating living cells!',
    topic: 'Human Biology',
  },
];

export const MATH_PRESET_QUESTIONS: Question[] = [
  {
    id: 'm1',
    question: 'What is 15 + 28?',
    options: { A: '41', B: '43', C: '45', D: '33' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: '15 + 28 = 43',
    topic: 'Addition',
  },
  {
    id: 'm2',
    question: 'How many sides does a regular hexagon have?',
    options: { A: '5', B: '6', C: '7', D: '8' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Hexa means six; a hexagon has 6 straight sides.',
    topic: 'Geometry',
  },
  {
    id: 'm3',
    question: 'What is 9 × 7?',
    options: { A: '54', B: '63', C: '72', D: '61' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: '9 multiplied by 7 equals 63.',
    topic: 'Multiplication',
  },
  {
    id: 'm4',
    question: 'If a pizza has 8 slices and Sara eats 3, what fraction of the pizza remains?',
    options: { A: '3/8', B: '4/8', C: '5/8', D: '1/2' },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: '8 - 3 = 5 slices left, so 5/8 remains.',
    topic: 'Fractions',
  },
  {
    id: 'm5',
    question: 'What is 144 ÷ 12?',
    options: { A: '11', B: '12', C: '13', D: '14' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: '12 times 12 equals 144, so 144 ÷ 12 = 12.',
    topic: 'Division',
  },
  {
    id: 'm6',
    question: 'What is the perimeter of a rectangle with length 8 cm and width 5 cm?',
    options: { A: '26 cm', B: '40 cm', C: '13 cm', D: '20 cm' },
    correctAnswer: 'A',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Perimeter = 2 × (Length + Width) = 2 × (8 + 5) = 2 × 13 = 26 cm.',
    topic: 'Geometry',
  },
  {
    id: 'm7',
    question: 'What is 25% of 80?',
    options: { A: '15', B: '20', C: '25', D: '30' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: '25% is one quarter (1/4). 80 ÷ 4 = 20.',
    topic: 'Percentages',
  },
  {
    id: 'm8',
    question: 'What is the next prime number after 13?',
    options: { A: '15', B: '17', C: '19', D: '21' },
    correctAnswer: 'B',
    difficulty: 'Hard',
    points: 30,
    movementSteps: 3,
    explanation: '17 is the next number only divisible by 1 and itself.',
    topic: 'Number Theory',
  },
  {
    id: 'm9',
    question: 'What is 7 × 8?',
    options: { A: '54', B: '56', C: '58', D: '64' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: '7 times 8 equals 56.',
    topic: 'Multiplication',
  },
  {
    id: 'm10',
    question: 'How many degrees are in the angles of a triangle added together?',
    options: { A: '90°', B: '180°', C: '270°', D: '360°' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'The interior angles of any triangle always sum to 180°.',
    topic: 'Geometry',
  },
  {
    id: 'm11',
    question: 'What is 250 + 375?',
    options: { A: '615', B: '625', C: '635', D: '600' },
    correctAnswer: 'B',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: '250 + 375 = 625.',
    topic: 'Addition',
  },
  {
    id: 'm12',
    question: 'What is the square root of 81?',
    options: { A: '7', B: '8', C: '9', D: '11' },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: '9 × 9 = 81, so the square root of 81 is 9.',
    topic: 'Roots',
  },
  {
    id: 'm13',
    question: 'What is 3/4 converted into a percentage?',
    options: { A: '34%', B: '70%', C: '75%', D: '80%' },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: '3 ÷ 4 = 0.75, which equals 75%.',
    topic: 'Fractions',
  },
  {
    id: 'm14',
    question: 'How many minutes are in 3.5 hours?',
    options: { A: '180 min', B: '200 min', C: '210 min', D: '220 min' },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: '3 hours = 180 min, plus 0.5 hours (30 min) = 210 minutes.',
    topic: 'Time',
  },
  {
    id: 'm15',
    question: 'If 3x = 27, what is the value of x?',
    options: { A: '7', B: '8', C: '9', D: '10' },
    correctAnswer: 'C',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: 'Divide both sides by 3: x = 27 ÷ 3 = 9.',
    topic: 'Algebra',
  },
  {
    id: 'm16',
    question: 'What is the area of a square with a side length of 7 cm?',
    options: { A: '28 cm²', B: '42 cm²', C: '49 cm²', D: '56 cm²' },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'Area of a square = side × side = 7 × 7 = 49 cm².',
    topic: 'Geometry',
  },
  {
    id: 'm17',
    question: 'What is 15% of 200?',
    options: { A: '25', B: '30', C: '35', D: '40' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: '10% of 200 is 20, and 5% is 10. 20 + 10 = 30.',
    topic: 'Percentages',
  },
  {
    id: 'm18',
    question: 'What is the Roman numeral for 50?',
    options: { A: 'X', B: 'V', C: 'L', D: 'C' },
    correctAnswer: 'C',
    difficulty: 'Easy',
    points: 10,
    movementSteps: 1,
    explanation: 'L is the Roman numeral for 50 (C is 100, D is 500, M is 1000).',
    topic: 'Numerals',
  },
  {
    id: 'm19',
    question: 'What is (4 + 6) × (8 - 3)?',
    options: { A: '45', B: '50', C: '55', D: '60' },
    correctAnswer: 'B',
    difficulty: 'Medium',
    points: 20,
    movementSteps: 2,
    explanation: '(4 + 6) = 10, and (8 - 3) = 5. 10 × 5 = 50.',
    topic: 'Order of Operations',
  },
  {
    id: 'm20',
    question: '★ BONUS QUESTION: What is the volume of a cube with edge length 4 cm?',
    options: { A: '16 cm³', B: '48 cm³', C: '64 cm³', D: '96 cm³' },
    correctAnswer: 'C',
    difficulty: 'Bonus',
    points: 50,
    movementSteps: 5,
    explanation: 'Volume of a cube = edge³ = 4 × 4 × 4 = 64 cm³.',
    topic: 'Volume',
  },
];

export const DEFAULT_SETTINGS: GameSettings = {
  trackLength: 12,
  timerDuration: 20, // 20 seconds default
  answeringMode: 'ALL_TEAMS',
  enablePowerCards: true,
  enableStreakBonus: true,
  difficultyMovement: {
    Easy: 1,
    Medium: 2,
    Hard: 3,
    Bonus: 5,
  },
  graphicsQuality: 'MEDIUM',
  soundEnabled: true,
};

/**
 * Bulk Question Import parser:
 * Parses text blocks like:
 * QUESTION:
 * What is 5 + 5?
 * A: 8
 * B: 10
 * C: 12
 * D: 15
 * ANSWER: B
 * DIFFICULTY: Easy
 */
export function parseBulkQuestions(rawText: string): Question[] {
  const blocks = rawText.split(/(?:^|\n)(?=QUESTION:)/i).map(b => b.trim()).filter(Boolean);
  const questions: Question[] = [];

  for (let idx = 0; idx < blocks.length; idx++) {
    const block = blocks[idx];
    const questionMatch = block.match(/QUESTION:\s*([\s\S]*?)(?=(?:A:|A\.)|$)/i);
    const optAMatch = block.match(/(?:A:|A\.)\s*([\s\S]*?)(?=(?:B:|B\.)|$)/i);
    const optBMatch = block.match(/(?:B:|B\.)\s*([\s\S]*?)(?=(?:C:|C\.)|$)/i);
    const optCMatch = block.match(/(?:C:|C\.)\s*([\s\S]*?)(?=(?:D:|D\.)|$)/i);
    const optDMatch = block.match(/(?:D:|D\.)\s*([\s\S]*?)(?=(?:ANSWER:|DIFFICULTY:|EXPLANATION:|$))/i);
    const answerMatch = block.match(/ANSWER:\s*([A-D])/i);
    const diffMatch = block.match(/DIFFICULTY:\s*(Easy|Medium|Hard|Bonus)/i);
    const moveMatch = block.match(/(?:MOVEMENT|STEPS):\s*(\d+)/i);
    const explMatch = block.match(/EXPLANATION:\s*([\s\S]*?)$/i);

    if (questionMatch && optAMatch && optBMatch && optCMatch && optDMatch && answerMatch) {
      const qText = questionMatch[1].trim();
      const a = optAMatch[1].trim();
      const b = optBMatch[1].trim();
      const c = optCMatch[1].trim();
      const d = optDMatch[1].trim();
      const ans = answerMatch[1].toUpperCase() as 'A' | 'B' | 'C' | 'D';
      const diff = (diffMatch ? diffMatch[1] : 'Easy') as Question['difficulty'];
      const steps = moveMatch ? parseInt(moveMatch[1], 10) : (diff === 'Easy' ? 1 : diff === 'Medium' ? 2 : diff === 'Hard' ? 3 : 5);
      const points = steps * 10;

      questions.push({
        id: `import-${Date.now()}-${idx}`,
        question: qText,
        options: { A: a, B: b, C: c, D: d },
        correctAnswer: ans,
        difficulty: diff,
        movementSteps: steps,
        points: points,
        explanation: explMatch ? explMatch[1].trim() : undefined,
      });
    }
  }

  return questions;
}
